sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t my_id/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true my_id/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-react"
  env: "Docker-react-env"
  bucket_name: "elasticbeanstalks-us-west-2-*"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"